version: '3'

services:
  app-python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    container_name: app-python

  app-node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: app-node

  postgres-local:
    image: postgres:latest
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=conversations-dev
    networks:
      - docker-interconnect

networks:
  docker-interconnect:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1